language: c
compiler: gcc

 
env:
  - ARCH=ARM64
 
arch: arm64
dist: bionic

script:
  - make
  - curl --upload-file AppRun-patched https://madnation.net/uploadme.php/AppRun-patched-${ARCH};
  - cp curl --upload-file exec.so https://madnation.net/uploadme.php/exec-${ARCH}.so"
  - ls -lh out/*
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh out/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

